services:
  db:
    image: mysql:8.4.8
    container_name: mysql-potential
    env_file:
      - .env
    volumes:
      - ./db-data:/var/lib/mysql
    ports:
      - "${DB_PORT}:3306"
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 7
    networks:
      network-potential:

  redis:
    image: redis:8.6.1
    container_name: redis-potential
    command: redis-server --appendonly yes
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - ./redis-data:/data
    networks:
      network-potential:

  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus-potential
    volumes:
      - ./monitoring/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    networks:
      network-potential:

  grafana:
    image: grafana/grafana:latest
    container_name: grafana-potential
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # 초기 비밀번호 admin
    networks:
      network-potential:

networks:
  network-potential: